name: befit

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: befit
      POSTGRES_USER: ${POSTGRES_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    env_file:
      - .env.local

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_SERVER_JSON_FILE: /pgadmin/servers.json
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env.local

  befit:
    container_name: befit
    pull_policy: build
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev,dummy-data  # Add dummy-data profile to automatically clear en fill the database on startup
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/befit
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_ADMIN_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      DISCORD_TOKEN: ${BEFIT_DISCORD_TOKEN}
      DISCORD_GUILDS_MANAGEMENT: ${BEFIT_DISCORD_GUILDS_MANAGEMENT}
      DISCORD_DUMMY_USER_ID: ${BEFIT_DISCORD_DUMMY_USER_ID}
      BEFIT_TIMEFORMAT: ${BEFIT_TIMEFORMAT}
      BEFIT_DATEFORMAT: ${BEFIT_DATEFORMAT}
    env_file:
      - .env.local

volumes:
  postgres-data:
  postgres-backups:
  pgadmin-data:
