name: befit

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: befit
      POSTGRES_USER: ${POSTGRES_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    env_file:
      - .env

  postgres-backup:
    image: kartoza/pg-backup:16-3.4
    container_name: postgres-backup
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USERNAME}
      POSTGRES_PASS: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      DBLIST: befit
      REMOVE_BEFORE: 90
      CRON_SCHEDULE: "0 0 * * *"
    volumes:
      - postgres-backups:/backups
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_SERVER_JSON_FILE: /pgadmin/servers.json
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env

  befit:
    image: ghcr.io/jordybronowicki37/befit:latest
    container_name: befit
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/befit
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_ADMIN_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      DISCORD_TOKEN: ${BEFIT_DISCORD_TOKEN}
      DISCORD_GUILDS_MANAGEMENT: ${BEFIT_DISCORD_GUILDS_MANAGEMENT}
    env_file:
      - .env

volumes:
  postgres-data:
  postgres-backups:
  pgadmin-data:
