#SQL logging
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    discord4j: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        security: DEBUG
        web:
          client:
            RestTemplate: DEBUG
    dev:
      jb: DEBUG
