spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/befit
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

discord:
  token: token
  channels:
    motivational: channel-id

