name: Build and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        description: The image name
        required: false
        type: string
        default: befit
      version:
        description: The image version
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image_name:
        description: The image name
        required: false
        type: string
        default: befit
      version:
        description: The image version
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: install buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push the Docker image
        run: docker buildx build --push --platform linux/arm64/v8,linux/amd64 --file Dockerfile --tag ghcr.io/${{ github.actor }}/${{ inputs.image_name }}:${{ inputs.version }} .
        working-directory: backend
