name: Feature release
on:
  push:
    branches:
      - main

jobs:
  test-application:
    uses: ./.github/workflows/test-application.yml

  update-dependency-graph:
    uses: advanced-security/maven-dependency-submission-action@v5

  bump-tag-version:
    needs: test-application
    permissions:
      contents: write
    uses: ./.github/workflows/bump-tag.yml

  build-and-publish:
    needs: bump-tag-version
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/create-docker-image.yml
    with:
      version: ${{ needs.bump-tag-version.outputs.tag }}
